# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc31bb6de9b86efa99d14a0865f31f51c89e864d72ef2a1642f17a47ea4ff018098bcedab779ebc7e8bab0895017f20b1d0abed0e618da0223de07b65764fb7d

test:
  secret_key_base: 35839ae3b06d210c242beb09d8a607320d8c85ba56a8e1640d6ecb960a049fbeff6673e74fbbfcf273796ee9a5fa2e5c213b29d66275fe1334471c0d0643bc96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
